name: CI/CD for Nellie Borrero Site

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    uses: ronald50928/.github/.github/workflows/node-build.yml@main
    with:
      working-directory: 'site'
      cache-dependency-path: 'site/package.json'
    secrets: inherit

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    uses: ronald50928/.github/.github/workflows/s3-cloudfront-deploy.yml@main
    with:
      s3-bucket: ${{ secrets.S3_BUCKET }}
      cloudfront-distribution-id: ${{ secrets.CF_DISTRIBUTION_ID }}
      build-artifact-name: ${{ needs.build.outputs.build-artifact-name }}
      working-directory: 'site'
      role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
      aws-region: 'us-east-1'
    secrets: inherit
